// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgxairafkxkiqasaphep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhneGFpcmFma3hraXFhc2FwaGVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMDYyMTIsImV4cCI6MjA1NDU4MjIxMn0.0RRn8POlfEXvuXLf3PLKODSoVIyeGyvd2pCt4wv3hnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);